title = "joselyn rodriguez"
baseURL = "https://joselynrodriguez.com"
theme = "cactus"
copyright = "jmr" # cactus will use title if copyright is not set

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "research"
url = "/research/research"
weight = 2

[[menu.main]]
name = "blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "cv"
url = "/files/cv.pdf"
weight = 4

[[menu.main]]
name = "misc"
url = "/music/playlisting/"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = """

  Hi! I'm a third year PhD student in Neuroscience and Cognitive Science at the University of Maryland. 
  I'm housed in the Department of Linguistics and am advised by [Dr. Naomi Feldman](http://users.umiacs.umd.edu/~nhf/) and [Dr. Bill Idsardi](https://wjidsardi.net/). 

  Prior to coming to UMD, I worked as a lab assistant and graduate student with [Dr. Dave Kleinschmidt](http://davekleinschmidt.com) in the Department of Psychology at Rutgers University.

  My research focuses on computational modeling of speech perception and learning (and occasionally behavioral and neuroimaging experiments). The questions that interest me most are those surrounding second language acquisition.
  How do we learn a second language? How is this process different than how we learn our first language?
  
  I'm joined at UMD by the other members of my linguistics cohort, [Katherine Howitt](https://www.katherinehowitt.com/research), Jingyi Chen, [London Dixon](https://www.londondixon.com/) , Fëdor Golosov, Zulfiyya Aghakishiyeva.
  """ 
  
  mainSection = "posts" # your main section
  mainSectionTitle = "..."
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 0 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).

#   projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/joselyn-rodriguez"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/joselyn-rodriguez/"
  [[params.social]]
    name = "email"
    link = "jrodri20@umd.edu"  # no need for "mailto:" in the heads
  [[params.social]]
    name = "spotify"
    link = "https://open.spotify.com/user/cho_seul_lin?si=ba2c72321e1948e7"
